name: Audit Request
description: Request from a manufacturer of a controller for evaluation of a product.
title: "[AUDIT REQUEST]: "
labels: ["audit request", "triage"]
assignees:
  - ziesemer
body:
  - type: input
    id: manufacturer
    attributes:
      label: Manufacturer
      description: Manufacturer Name
      placeholder: Manufacturer Name
    validations:
      required: true
  - type: input
    id: model
    attributes:
      label: Model
      description: Model Name / Number / SKU
      placeholder: Model Name / Number / SKU
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Product Link
      description: Link to Product Page
      placeholder: https://
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email
      description: Contact email address for any needed private communications outside of this GitHub issue, such as for shipping instructions and addresses, etc.
      placeholder: support@example.com
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context / Details
      description: Any additional context / details to be included in the request.
      render: markdown
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: By submitting this issue, I indicate that I have read, understand, and accept the requirements and process of the [Audit Request](docs/Audit-Requests.md) document.
      options:
        - label: "I have read, understand, and accept the requirements and process of this project's [Audit Request](docs/Audit-Requests.md) document."
          required: true
